/**
 * lib/ai.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Mock AI integration — replace the implementations below with real
 * OpenAI / Anthropic Claude API calls when you're ready.
 *
 * TODO (real integration):
 *   import OpenAI from "openai";
 *   const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
 *
 * OR for Claude:
 *   import Anthropic from "@anthropic-ai/sdk";
 *   const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
 */

import type {
  GenerateVerseOptions,
  GenerateVerseResult,
  FixErrorOptions,
  FixErrorResult,
} from "@/types";

// ─── Verse Code Generator ─────────────────────────────────────────────────────

export async function generateVerseCode(
  options: GenerateVerseOptions
): Promise<GenerateVerseResult> {
  // Simulate network latency
  await new Promise((r) => setTimeout(r, 2200));

  const { description, mapType, difficulty, outputType } = options;

  // ── Mock verse code ──────────────────────────────────────────────────────────
  const code = `using { /Fortnite.com/Devices }
using { /Verse.org/Simulation }
using { /UnrealEngine.com/Temporary/Diagnostics }

# Generated by VersePilot — ${mapType} / ${difficulty}
# System: ${description}
#
# TODO: Replace this mock with a real AI-generated implementation.

verse_system_device := class(creative_device):

    # ── Device references — assign in UEFN editor ──────
    @editable TriggerZone  : trigger_device  = trigger_device{}
    @editable EconomyDev   : economy_device  = economy_device{}

    var PlayerData : [player]int = map{}

    OnBegin<override>()<suspends> : void =
        TriggerZone.TriggeredEvent.Subscribe(OnTriggered)
        Print("[VersePilot] System initialised.")

    OnTriggered(Agent : agent) : void =
        if (Player := player[Agent]):
            CurrentVal := if (V := PlayerData[Player]) then V else 0
            if (set PlayerData[Player] = CurrentVal + 1) {}
            HandlePlayer(Player, CurrentVal + 1)

    HandlePlayer(Player : player, Count : int)<suspends> : void =
        EconomyDev.AddResource(Player, 100)
        Print("Player interaction #{Count} processed.")`;

  // ── Device setup ─────────────────────────────────────────────────────────────
  const deviceSetup = `## Device Setup — ${mapType} Map

### Required Devices
- **trigger_device** — place at entry zone, set Channels as needed
- **economy_device** — tracks player resource counts (gold/coins)

### Steps
1. Open UEFN and create a new Verse file via the Content Browser.
2. Paste the generated code and push it to the island.
3. Drag the devices listed above into the map.
4. Select your Verse device → Properties panel → assign each @editable field.
5. Set trigger extents to cover the intended area.
6. Playtest with \`Play in Editor\`.

### Recommended Settings
| Device | Setting | Value |
|--------|---------|-------|
| trigger_device | Activation Channels | 1 |
| economy_device | Initial Resource | 0 |`;

  // ── Explanation ──────────────────────────────────────────────────────────────
  const explanation =
    outputType === "Code only"
      ? ""
      : `## How This System Works

This device implements a **${description}** for a ${mapType} map at ${difficulty} level.

### Key Concepts

**\`OnBegin<override>()<suspends>\`**
The entry point for every creative_device. The \`<suspends>\` modifier means the function can \`Sleep()\` without blocking other systems.

**\`TriggeredEvent.Subscribe()\`**
Registers a callback that fires every time the trigger activates. Verse uses event-driven architecture — you don't poll; you subscribe.

**\`player[Agent]\`**
Safely casts an \`agent\` to a \`player\`. This is required because AI bots are also agents. The cast fails for NPCs, so only real players proceed.

**\`map{}\` for per-player state**
The \`[player]int\` map stores one integer per player. Always check for key existence before reading (\`if (V := Map[Player])\`).

### Flow Diagram
\`\`\`
Player enters zone
      ↓
OnTriggered fires
      ↓
Cast agent → player (fails for NPCs)
      ↓
Read / update PlayerData map
      ↓
Award resources via economy_device
\`\`\``;

  // ── Common errors ────────────────────────────────────────────────────────────
  const commonErrors = `## Common Errors & Fixes

### \`error: 'player' is not 'agent'\`
**Cause:** Passing an \`agent\` where a \`player\` is expected.
**Fix:** Use the \`player[Agent]\` guard pattern: \`if (P := player[Agent]) { ... }\`.

---

### \`error: use of uninitialized @editable device\`
**Cause:** You forgot to assign a device in the UEFN Properties panel.
**Fix:** Select the Verse device actor, open Properties, and drag the correct device into every @editable slot.

---

### \`error: map read without existence check\`
**Cause:** Writing \`PlayerData[Player]\` on the right-hand side without a guard.
**Fix:** Use: \`if (V := PlayerData[Player]) { ... } else { ... }\`.

---

### Device appears in map but events don't fire
**Cause:** Verse file was not pushed after the last save.
**Fix:** Open Verse Explorer → right-click → Push to Island. Wait for compile.`;

  return {
    code,
    deviceSetup,
    explanation,
    commonErrors,
  };
}

// ─── Error Fixer ──────────────────────────────────────────────────────────────

export async function fixVerseError(
  options: FixErrorOptions
): Promise<FixErrorResult> {
  // Simulate latency
  await new Promise((r) => setTimeout(r, 1800));

  const { errorMessage, code } = options;

  // Detect common error patterns for a smarter mock response
  if (errorMessage.toLowerCase().includes("uninitialized")) {
    return {
      problem: `**Uninitialized @editable Device Reference**

The error indicates that one of your \`@editable\` device fields was not assigned in the UEFN Properties panel. Verse initialises it as an empty default object, meaning event subscriptions and method calls have no effect — or crash silently.`,
      fixedCode: code.replace(
        /(@editable\s+\w+\s*:\s*\w+)\s*=/g,
        "$1 = // ← ASSIGN in UEFN editor"
      ),
      explanation: `Select your Verse device actor in the UEFN Outliner, open the Details / Properties panel, and drag the correct device from the map into each orange @editable slot. Every @editable must be assigned before playtesting.`,
      preventionTip: `Add a runtime guard in OnBegin: check that your device reference is valid (e.g., attempt a no-op call) before subscribing to events.`,
    };
  }

  if (
    errorMessage.toLowerCase().includes("suspends") ||
    errorMessage.toLowerCase().includes("no effect context")
  ) {
    return {
      problem: `**Missing \`<suspends>\` Context**

You called a suspending function (like \`Sleep()\`) from a non-suspending context. In Verse, every function that \`Sleep()\`s or calls a suspending function must itself be marked \`<suspends>\`.`,
      fixedCode: code.replace(
        /(\w+)\(\)<\/?\s*void/g,
        "$1()<suspends> : void"
      ),
      explanation: `Add \`<suspends>\` to the function signature: \`MyFunction()<suspends> : void\`. If this is an event handler, wrap the async work in a \`spawn{}\` block instead of making the handler itself suspending.`,
      preventionTip: `Use \`spawn{ AsyncWork(Player) }\` inside event handlers to keep them lightweight, and reserve \`<suspends>\` for the actual async coroutine.`,
    };
  }

  // Generic fallback
  return {
    problem: `**Detected Error:** \`${errorMessage.slice(0, 120)}\`

This appears to be a type or scope issue in your Verse code. The most common causes are:
- Incorrect type cast (e.g., using \`agent\` where \`player\` is needed)
- Missing \`<override>\` on lifecycle methods
- Accessing a map key without an existence guard`,
    fixedCode: `${code}

# ── VersePilot suggestion ──────────────────────────────
# Review these common patterns:
#
# 1. Player cast guard:
#    if (P := player[Agent]) { ... }
#
# 2. Map read with fallback:
#    Val := if (V := MyMap[Key]) then V else 0
#
# 3. Lifecycle override:
#    OnBegin<override>()<suspends> : void = ...`,
    explanation: `Check that all agents are cast to players before use, that map accesses are guarded with \`if (V := Map[Key])\`, and that \`OnBegin\` carries both \`<override>\` and \`<suspends>\`.`,
    preventionTip: `Run "Verse: Verify" in the Verse Explorer before pushing — it catches most type errors at author time.`,
  };
}
